# Generated by Django 4.1.3 on 2022-11-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_alter_lyric_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='content',
            field=models.TextField(max_length=10000),
        ),
    ]
